### ISSUE TITLE
Schema Comments

### ISSUE THREAD

**Issue by chf2** [gmkohler/HoundCloud#6]
### Tags
- Tags names should probably be unique. 
### Playlists
- This seems to have been left off of the plans for the API in the implementation timeline.
### playlist_comments
- This seems to be missing at least a body field

**Comment by gmkohler** [comment]
I moved playlists to the deep end of bonus after realizing how complicated they are, and forgot to reflect this change in the schema.  Will re-organize schema accordingly.
